language: scala
sudo: false
addons:
  postgresql: "9.4"
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
- openjdk11
script:
- sbt "^^ ${SBT_VERSION}" scripted
- git diff --exit-code # check scalariform
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
env:
  matrix:
  - SBT_VERSION="0.13.18"
  - SBT_VERSION="1.2.8"
